### ISSUE TITLE
Sub-transaction for trade_cleanup.sql Frame 1 

### ISSUE THREAD

**Issue by MaheshGouru** [osdldbt/dbt5#1]
In reference to the nested while loop in the main transaction loop

https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_cleanup.sql#L81

**Comment by markwkm** [comment]
@MaheshGouru Can you explain the work that needs to be done here?  High level description is ok.  In other words where do the transaction control statements need to go?

**Comment by markwkm** [comment]
After reviewing the spec, this isn't a transaction that uses subtransactions.
