### ISSUE TITLE
brokeragehousemain, marketexchangemain, drivermain not properly handling uppercase arguments

### ISSUE THREAD

**Issue by markwkm** [osdldbt/dbt5#23]
It feels like the command-line arguments are case insensitive...  maybe should try to make itsensitive.

**Comment by mw2q** [comment]
Fixed in 70115c17e49db30db7a36313ec68166dc2e093f5.

**Comment by markwkm** [comment]
Addressed in 70115c17e49db30db7a36313ec68166dc2e093f5.
