### ISSUE TITLE
Build commands in CMakeList.txt

### ISSUE THREAD

**Issue by huawendi** [osdldbt/dbt5#26]
Why delete all `ADD_EXECUTABLE` in _Cmakelists.txt_? I can't build my change of dbt5/src

**Comment by markwkm** [comment]
I'm guess this was my attempt to use loops.  Can you confirm which revision you are working with, and show the output.  Let's see if I can reproduce it.

**Comment by huawendi** [comment]
This is my problem. I found that building of all code is moved into egen in [this commit](https://github.com/osdldbt/dbt5/commit/d154af0ba9452c476d049cf91bfff59858dee9b3). By executing `dbt5-build-egen`, all code can be built.
