### ISSUE TITLE
Sub-transaction for trade_order.sql Frame 6

### ISSUE THREAD

**Issue by MaheshGouru** [osdldbt/dbt5#7]
[storedproc/pgsql/pgsql/trade_order.sql](https://github.com/osdldbt/dbt5/blob/main/storedproc/pgsql/pgsql/trade_order.sql#L528)

**Note: Trade_Order.SQL, Frames 5 & 6 are not implemented for the rollback or commit transaction**

The sub-transaction control should be added as the commit transaction are identified in the TPC-Ev1.14 Pseudo-code (Page 139 of 287).

Starting the sub-transaction would be after [line 528](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_order.sql#L528)

The preliminary conversion to a stored procedure would be implemented by adhering to convention and adding Frame 6 after the "RETURN trade_id;" on [line 528](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_order.sql#L528). 

There is an COMMIT call in the 3.3.7.2 Trade-Order Transaction Database Footprint and the Trade-Order_Frame-6 Pseudo-code to implement.

Updating the CREATE FUNCTION with CREATE PROCEDURE on [line 528](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_order.sql#L528)

The parameter changes to handle the return values would be after [line 528](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_order.sql#L528) as the customer, customer's account, and the broker for the account would be referenced. (Page 122 of 287)

> **3.3.7 The Trade-Order Transaction**
>>...
>>The Trade-Order **Transaction** is invoked by the **EGenDriverCE**. It consists of six **Frames**. The **Transaction** starts by using the account ID passed into the **Transaction** to obtain information on the customer, the customer's account, and the broker for the account.
>>...

---
Modification to the C++ code to call the procedure would be on [line 170](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/src/transactions/TradeOrderDB.cpp#L170) of [dbt5/TradeOrderDB.cpp](https://github.com/osdldbt/dbt5/blob/main/src/transactions/TradeOrderDB.cpp)

**Comment by markwkm** [comment]
This frame doesn't need to be rewritten.  The C++ code can handle the transaction control requirements because subtransactions aren't needed.
