### ISSUE TITLE
Sub-transaction for trade_result.sql Frame 6

### ISSUE THREAD

**Issue by MaheshGouru** [osdldbt/dbt5#8]
[storedproc/pgsql/pgsql/trade_order.sql](https://github.com/osdldbt/dbt5/blob/main/storedproc/pgsql/pgsql/trade_result.sql)

The sub-transaction control should be added as the commit transaction are identified in the TPC-Ev1.14 Pseudo-code (Page 159 of 287).

Starting the sub-transaction would be after [line 597](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_result.sql#L597)

The preliminary conversion to a stored procedure would be implemented by adhering to convention and adding Frame 6's commit after the "WHERE	CA_ID = acct_id;" on [line 620](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_result.sql#L620). 

There is no ROLLBACK call in neither the 3.3.8.2 Trade-Result Transaction Database Footprint nor the Trade-Result_Frame-6 Pseudo-code to implement.

Updating the CREATE FUNCTION with CREATE PROCEDURE on [line 581](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_result.sql#L581)

The parameter changes to handle the return values would be after [line 622](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/trade_result.sql#L622).

---
Modification to the C++ code to call the procedure would be on [line 154](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/src/transactions/TradeResultDB.cpp#L193) of [dbt5/TradeResultDB.cpp](https://github.com/osdldbt/dbt5/blob/main/src/transactions/TradeResultDB.cpp)

**Comment by markwkm** [comment]
This frame doesn't need to be rewritten.  The C++ code can handle the transaction control requirements without subtransactions.
