### ISSUE TITLE
Sub-transaction for data_maintenance.sql Frame 1

### ISSUE THREAD

**Issue by MaheshGouru** [osdldbt/dbt5#9]
[storedproc/pgsql/pgsql/trade_order.sql](https://github.com/osdldbt/dbt5/blob/main/storedproc/pgsql/pgsql/data_maintenance.sql)

The sub-transaction control should be added as the commit transaction are identified in the TPC-Ev1.14 Pseudo-code (Page 190 of 287).

Starting the sub-transaction would be at [line 51](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/data_maintenance.sql#L51)

The preliminary conversion to a stored procedure would be implemented by adhering to convention and modifying Frame 1 on [line 51](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/data_maintenance.sql#L51) as after [line 345](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/data_maintenance.sql#L345) there should be the COMMIT. 

There is neither a ROLLBACK call in the 3.3.11.2 Data-Maintenance Transaction Database Footprint and the Data-Maintenance_Frame-1 Pseudo-code to implement.

Updating the CREATE FUNCTION with CREATE PROCEDURE on [line 16](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/data_maintenance.sql#L16)

There would be no parameter changes to handle the return values at [line 345](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/storedproc/pgsql/pgsql/data_maintenance.sql#L345).

---
Modification to the C++ code to call the procedure would be on [line 34](https://github.com/osdldbt/dbt5/blob/d9170b8be92624024fa1f65cfad765602da4915c/src/transactions/DataMaintenanceDB.cpp#L34) of [dbt5/DataMaintenanceDB.cpp](https://github.com/osdldbt/dbt5/blob/main/src/transactions/DataMaintenanceDB.cpp)

**Comment by markwkm** [comment]
The data maintenance tarnsaction doesn't need subtransactions.
